### ISSUE TITLE
Build dependencies?

### ISSUE THREAD

**Issue by sparre-consafe** [AdaCore/gpr#1]
Current gpr-tools only support inclusion of other projects (using "with"), but what about build-dependencies?

- Libraries, which have to be built, before the project can be linked.
- Code generators, which have to run, before all the sources are available for compilation
- ...

Is this a part of the plan for "gpr2"?

**Comment by TurboGit** [comment]
Yes and no. LibGPR2 will allow multi-phase builds but even if all the support is in LibGPR2 the GPR tools will have to handle this.

**Comment by t-14** [comment]
This is definitely on our roadmap, but it's in preliminary design phase yet. As a sneak preview, the current idea is to introduce new attributes Project'Stages to define possible stages, and Project'Stage to refer to an individual stage and assign properties to it. The new feature will be syntactically similar to scenario variables, but whereas a scenario only has a specific given value in a given view, the Stage attribute has all values at once (i.e. a stages-aware tool will need to iterate through stages).

The new functionality could be used like this:

`
  with "imp";
   ...
  for Stages use Imp'Stages & ("generate", "build");
  --  'Stage attribute is read-only.
  case Project'Stage is
     when "generate" =>
        for Languages use ("Simulink");
        for Source_Dirs use ("src1");
        for Object_Dir use "src2";
     when "build" =>
        for Languages use ("Ada");
        for Source_Dirs use ("src2");
  end case;
`

Notice how objects of the "generate" stage serve as sources of the "build" stage.

As mentioned above, implementing the corresponding support in gpr2 is only part of the story, the tools (first and foremost gprbuild) will need to make use of it.
