### ISSUE TITLE
Curious warnings when building GPRName.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gpr#5]
```
% gprbuild -p -m -j0  -XGPR2_BUILD=debug -XGPR2_EDGE_TOOLS_PREFIX=gpr2 -XBUILD_ROOT="/Users/me/src-2022/gpr2-edge-23.0w-20220512-1618A-src/.build"  -XPROFILER=no  -XLIBRARY_TYPE=static -XXMLADA_BUILD=static \
  -XLANGKIT_SUPPORT_BUILD=static ./gpr2-name.gpr
...
Link
   [link]         gprname-main.adb
gprname-process.adb:63:45: warning: unable to locate objcopy
gprname-process.adb:63:14: warning: unable to locate objcopy
```
What are these warnings for?

**Comment by t-14** [comment]
gprbuild uses objcopy to record in the library the additional link options so that they can later be retrieved when linking the final application. If it can't find objcopy it will be unable to do it.

**Comment by Blady-Com** [comment]
Thanks for this information, I got it.
Nevertheless, the reference to `gprname-process.adb:63:45` is weird!?

**Comment by t-14** [comment]
Ah, good point. No idea what's that about (and for that matter, where would sloc information be coming from during the link stage anyway)... which gprbuild is being used?

**Comment by Blady-Com** [comment]
gprbuild is coming from Alire distribution (gprbuild_22.0.1_b1220e2b):
```
% gprbuild --version
GPRBUILD 22.0.0 (2021-11-09) (x86_64-apple-darwin19.6.0)
Copyright (C) 2004-2021, AdaCore
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by t-14** [comment]
Thanks! OBE anyway - it's related to your issue https://github.com/AdaCore/gprbuild/issues/123 which is essentially an uninitialized variable access, so any weird SLOC may show up.
