### ISSUE TITLE
Crash in gprclean in RTS build project

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gpr#9]
This was with v24.0.0.

## The crash
```
$ ~/local/bin/gprclean
using project file /Users/simon/Developer/bugs/gcc/gpr2/demo/stm32f4/build_runtime.gpr
gprclean: Fatal error: raised ADA.IO_EXCEPTIONS.NAME_ERROR : invalid simple name "../common"
Load address: 0x105f8a000
Call stack traceback locations:
0x106db7c9a 0x10675b2bc 0x106758c87 0x10679e438 0x10679787f 0x106765f7b 0x10676daf9 0x106784b09 0x1063b6e59 0x1060d5f85 0x105f8be93 0x105f9ffa2
```
## The traceback
```
lockheed:stm32f4 simon$ atos -o ~/local/bin/gprclean -l 0x105f8a000 0x106db7c9a 0x10675b2bc 0x106758c87 0x10679e438 0x10679787f 0x106765f7b 0x10676daf9 0x106784b09 0x1063b6e59 0x1060d5f85 0x105f8be93 0x105f9ffa2
ada__directories__compose (in gprclean) (a-direct.adb:180)
gpr2__project__tree__create_runtime_view__B_5__with_rtd_prefix.353 (in gprclean) (gpr2-project-tree.adb:419)
gpr2__project__tree__create_runtime_view (in gprclean) (gpr2-project-tree.adb:440)
gpr2__project__tree__set_context__2 (in gprclean) (gpr2-project-tree.adb:3399)
gpr2__project__tree__set_context (in gprclean) (gpr2-project-tree.adb:2488)
gpr2__project__tree__load__2 (in gprclean) (gpr2-project-tree.adb:1313)
gpr2__project__tree__load_autoconf__2 (in gprclean) (gpr2-project-tree-load_autoconf.adb:777)
gpr2__project__tree__load_autoconf (in gprclean) (gpr2-project-tree.adb:1443)
gpr2__options__load_project (in gprclean) (gpr2-options.adb:407)
gprtools__options__load_project__2 (in gprclean) (gprtools-options.adb:428)
_ada_gprclean__main (in gprclean) (gprclean-main.adb:677)
main (in gprclean) (b__gprclean-main.adb:2065)
$ 
```
## Investigation
In the attached `demo.zip`, the problem arises in the `ada_source_path`, which contains
```
adainclude
../common
../common/math
```
If we remove `ada_source_path`, `gprbuild` reports all the other things that are missing from this cut-down demo!

[demo.zip](https://github.com/AdaCore/gpr/files/14363330/demo.zip)

**Comment by lambourg** [comment]
Hello Simon,

Thank you for your report. I just checked and this issue is already fixed in master (see commit 1d33e0d). So using an up-to-date gprclean should do what you want here!

Best regards,
- Jerome

**Comment by simonjwright** [comment]
Thanks for the reply.

It took me some time to realise that gpr2 builds a lot of the same tools as gprbuild, whose gprclean doesn’t have this problem.

For v24.0.0 packaging I’ve only included the gprbuild versions.

**Comment by lambourg** [comment]
Ok, gpr2 will gradually replace all tools from gprbuild, next one being gprbuild itself. When this is done the gprbuild repository will be considered obsolete. In the mean time, the tools already available as part of gpr2 are the one that are maintained.
